### ISSUE TITLE
SSL 도입하기

### ISSUE THREAD

**Issue by potados99** [inu-appcenter/cafeteria-server#14]
HTTPS가 필요합니다.

**Comment by potados99** [comment]
카페테리아 안드로이드 3.1 출시 전에 신중하게 검토해보겠습니다.

**Comment by potados99** [comment]
이거이거 서두릅시다 제일 중요한거 아닙니까아

**Comment by potados99** [comment]
네 만들었습니다.

도메인도 만들었어요.

https://api.inucafeteria.gq/documentation

**Comment by bungabear** [comment]
@potados99 gq 최상위 도메인에 몇가지 이슈가 있어보입니다.
1. 1년 무료이후 갱신 비용이 매우 비쌉니다.  
2. DNS 문제가 있는것 같습니다. 모바일에서 접속 확인 부탁드립니다. (KT 5G/LTE 망에서 안됨)  
  
기존에 제가 https://freedns.afraid.org를 이용해 subdomain을 사용했었는데  
ssl을 발급 받을 수는 있었지만 공유도메인이라 문제의 소지가 있었고  
ssl이 인수인계 및 관리가 잘 안되다보니 미루고 있었습니다...

.com/.net 도메인 및 ssl 비용을 지원금으로 처리해보거나 subdomain 요청을 해보는건 어떨까요?

**Comment by potados99** [comment]
안녕하세요! 피드백 감사합니다! 😆

현재 my.freenom.com에서 제공하는 gq 도메인을 사용하고 있습니다. 

도메인 서비스를 찾던 중 마침 freenom에 계정이 있어 무료 gq 도메인을 임시로 사용하였습니다.

### 도메인 갱신 비용

갱신 비용을 보니 결코 저렴하지는 않은데요, 다행히 [무료 도메인은 만료 2주 전부터 무료로 갱신](https://my.freenom.com/knowledgebase.php?action=displayarticle&id=2)할 수 있다고 합니다.

### DNS 문제

DNS의 경우, 방금 KT 이동통신망 + iOS + 두 가지 브라우저(사파리, 크롬)으로 접속 시도해본 결과 응답이 지연되는 경우가 있긴 하였지만 정상적으로 접속은 되는 것을 확인하였습니다.

말씀해주신 이슈와 비슷한 상황이 DNS 레코드 변경 직후에도 일어났는데요, KT 유선망 연결된 개발 PC에서 nslookup 명령으로 CNAME을 가져오는 것에는 성공하였으나 브라우저는 5분 가량 해당 페이지를 열지 못하는 상황이 발생하였습니다.

도메인 제공자에 따르면 DNS 설정 변경이 완전히 적용되는 데에 72시간까지 걸릴 수도 있다고 합니다.

> Please note that it can take up to 72 hours for changes to a domain name or DNS settings to propagate globally.
[freenom 기술지원 페이지](https://my.freenom.com/knowledgebase.php?action=displayarticle&id=15)

내일까지 기다려보고, 안정적으로 연결되지 않으면 적용 딜레이의 문제가 아니라고 판단하고 다른 도메인으로 넘어가야겠습니다.

### SSL 인증서

다행히 인증서는 AWS Certificate Manager에서 무료로 발급받았습니다. 발급과 적용 절차가 간편하여 적용하는 데에 큰 어려움 없었습니다.

인증서를 서버에 직접 적용하기는 너무 번거로워서 아마존이 제공하는 로드 밸런서를 사용하였습니다. 아래와 같은 형태입니다.

~~~
로드 밸런서 HTTPS(443) -> nginx HTTP(8080) -> Node 인스턴스 HTTP(20201 또는 20202)
~~~

### Nginx

server_token off 지정하였습니다 :)
