### ISSUE TITLE
사용자 피드백을 받을 수 있어야 합니다.

### ISSUE THREAD

**Issue by potados99** [inu-appcenter/cafeteria-server#16]
카페테리아 모바일 앱 버전 2에 존재하던 피드백 기능을 복구해 주세요.

피드백에 답장도 왔으면 좋겠습니다 :)

**Comment by potados99** [comment]
의견 감사합니다. 

관리 기능 강화와 더불어 해당 기능 또한 검토중입니다. 진행 상황은 [프로젝트](https://github.com/inu-appcenter/cafeteria-server/projects/2) 참고 바랍니다.

**Comment by ryuspace** [comment]
뭐야

**Comment by potados99** [comment]
[1.1.0](https://github.com/inu-appcenter/cafeteria-server/releases/tag/v1.1.0) 버전에 추가했습니다 ^^
